language: php
sudo: required

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - TEST_COMMAND="composer test"

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install -o ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
  - $TEST_COMMAND

